### PR TITLE
Amend CrossRef DOI deposit output to conform to limit of 6 ISBNs (#379)

### LINKED ISSUE #379: Limit to 6 the number of ISBNs offered in CrossRef metadata export
**Describe the bug**
The [Crossref Metadata Input Schema v. 5.3.1](https://www.crossref.org/schemas/crossref5.3.1.xsd) accepts max 6 ISBNs in a single book DOI deposit. At present, Thoth doesn't seem to limit the number of ISBNs in the CrossRef metadata output.

**To Reproduce**
1. $`curl -X GET "https://export.thoth.pub/specifications/doideposit%3A%3Acrossref/work/2566ed3d-3df1-4e56-a7dc-455ecf7d3a4b"`
2. The output reports 7 ISBNs associated to the work.

**Expected behavior**
Limit the number of ISBNs to 6 in output.

**Desktop (please complete the following information):**
 - OS: Linux
 - Curl
 - Version 7.68.0

**Additional context**
Thank you!

### PR DESCRIPTION
**Pull request by rhigman**
Fixes #379. This is a workaround using logic specific to OBP's preferences.

CrossRef are currently investigating whether they can remove or increase this limit at their end (details linked in issue). If/when they do so, this fix should be removed or amended.

### CODE REVIEW

File: thoth-export-server/src/xml/doideposit_crossref.rs [hunk 1]
```diff
@@ -245,13 +245,30 @@ fn work_metadata<W: Write>(
...
+            // We raised this with CrossRef and they believe they should be able to increase the limit.
+            // Remove this workaround once this is done (see https://github.com/thoth-pub/thoth/issues/379).
+            // In the meantime, this is only encountered with OBP works, which have 7 ISBNs as standard.
+            // The least important of these is the HTML ISBN, so omit it.
+            if publications.len() > 6 {
+                if let Some(html_index) = publications
+                    .iter()
+                    .position(|p| p.publication_type == PublicationType::HTML)
+                {
+                    publications.swap_remove(html_index);
```
Comment (rhigman) [inline thoth-export-server/src/xml/doideposit_crossref.rs:265]: `swap_remove` used rather than `remove` for performance purposes. However, note that if an HTML ISBN is omitted and further ISBNs still need to be removed, the last-added ISBN will now have moved to the HTML ISBN's original position, so it may no longer be last in the list.

Hopefully it will be so rare that there are more than 7 ISBNs that this won't matter.

**Review by ja573 — APPROVED** [review]
